import axios from "axios";
import { TableData, TableRow } from "@/repo/main/typings/table";

const DATA_IBM = {
  Symbol: "IBM",
  AssetType: "Common Stock",
  Name: "International Business Machines",
  Description:
    "International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.",
  CIK: "51143",
  Exchange: "NYSE",
  Currency: "USD",
  Country: "USA",
  Sector: "TECHNOLOGY",
  Industry: "COMPUTER & OFFICE EQUIPMENT",
  Address: "1 NEW ORCHARD ROAD, ARMONK, NY, US",
  FiscalYearEnd: "December",
  LatestQuarter: "2023-06-30",
  MarketCapitalization: "127814148000",
  EBITDA: "12985000000",
  PERatio: "59.96",
  PEGRatio: "1.276",
  BookValue: "24.37",
  DividendPerShare: "6.61",
  DividendYield: "0.0473",
  EPS: "2.34",
  RevenuePerShareTTM: "66.75",
  ProfitMargin: "0.0335",
  OperatingMarginTTM: "0.141",
  ReturnOnAssetsTTM: "0.0411",
  ReturnOnEquityTTM: "0.104",
  RevenueTTM: "60524999000",
  GrossProfitTTM: "32688000000",
  DilutedEPSTTM: "2.34",
  QuarterlyEarningsGrowthYOY: "0.126",
  QuarterlyRevenueGrowthYOY: "-0.004",
  AnalystTargetPrice: "146",
  TrailingPE: "59.96",
  ForwardPE: "15.55",
  PriceToSalesRatioTTM: "2.108",
  PriceToBookRatio: "6.75",
  EVToRevenue: "2.969",
  EVToEBITDA: "25.81",
  Beta: "0.85",
  "52WeekHigh": "151.93",
  "52WeekLow": "110.02",
  "50DayMovingAverage": "144.41",
  "200DayMovingAverage": "135.56",
  SharesOutstanding: "911006000",
  DividendDate: "2023-09-09",
  ExDividendDate: "2023-08-09",
};

const DATA_AAPL = {
  Symbol: "AAPL",
  AssetType: "Common Stock",
  Name: "Apple Inc",
  Description:
    "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software, and online services. Apple is the world's largest technology company by revenue (totalling $274.5 billion in 2020) and, since January 2021, the world's most valuable company. As of 2021, Apple is the world's fourth-largest PC vendor by unit sales, and fourth-largest smartphone manufacturer. It is one of the Big Five American information technology companies, along with Amazon, Google, Microsoft, and Facebook.",
  CIK: "320193",
  Exchange: "NASDAQ",
  Currency: "USD",
  Country: "USA",
  Sector: "TECHNOLOGY",
  Industry: "ELECTRONIC COMPUTERS",
  Address: "ONE INFINITE LOOP, CUPERTINO, CA, US",
  FiscalYearEnd: "September",
  LatestQuarter: "2023-06-30",
  MarketCapitalization: "2676731412000",
  EBITDA: "123957002000",
  PERatio: "28.73",
  PEGRatio: "2.75",
  BookValue: "3.852",
  DividendPerShare: "0.93",
  DividendYield: "0.0056",
  EPS: "5.96",
  RevenuePerShareTTM: "24.22",
  ProfitMargin: "0.247",
  OperatingMarginTTM: "0.292",
  ReturnOnAssetsTTM: "0.209",
  ReturnOnEquityTTM: "1.601",
  RevenueTTM: "383932989000",
  GrossProfitTTM: "170782000000",
  DilutedEPSTTM: "5.96",
  QuarterlyEarningsGrowthYOY: "0.05",
  QuarterlyRevenueGrowthYOY: "-0.014",
  AnalystTargetPrice: "199.58",
  TrailingPE: "28.73",
  ForwardPE: "28.66",
  PriceToSalesRatioTTM: "5.51",
  PriceToBookRatio: "44.63",
  EVToRevenue: "5.92",
  EVToEBITDA: "23.52",
  Beta: "1.275",
  "52WeekHigh": "197.96",
  "52WeekLow": "123.64",
  "50DayMovingAverage": "181.27",
  "200DayMovingAverage": "166.22",
  SharesOutstanding: "15634200000",
  DividendDate: "2023-08-17",
  ExDividendDate: "2023-08-11",
};

const datas: any = {
  AAPL: DATA_AAPL,
  IBM: DATA_IBM,
};

export const getTableData = (symbols: string[]) => {
  return {
    queryKey: ["tableData", symbols],
    queryFn: async () => {
      const responses = await Promise.all(
        symbols.map((symbol: string) => {
          return datas[symbol];
        })
      );

      const result: TableRow[] = symbols.map((symbol, index) => ({
        name: responses[index].Name,
        description: responses[index].Description,
        address: responses[index].Address,
        dividendYield: responses[index].DividendYield,
        marketCapitalization: responses[index].MarketCapitalization,
      }));
      return result;
    },
    // queryFn: () => services.overview({ symbol }).then((data) => data.data),
    cacheTime: 5 * 60 * 1000,
  };
};
